### ISSUE TITLE
Unresolved reference: libs

### ISSUE THREAD

**Issue by splashhr** [solrudev/Ackpine#55]
![image](https://github.com/solrudev/Ackpine/assets/166183711/72910b24-0a1e-4eed-b9d2-1b75ec961ebc)

 samples don't work

**Comment by solrudev** [comment]
@splashhr I see that your root project directory is `sample-ktx`, so you most probably don't have the Ackpine library code and `gradle` directory with `libs.versions.toml` file in it, about absence of which Gradle is complaining. Clone the whole repo and then build the sample.

**Comment by splashhr** [comment]
thx
