### ISSUE TITLE
`Session {id} is dead.` failure

### ISSUE THREAD

**Issue by solrudev** [solrudev/Ackpine#84]
>@solrudev 

>> Does an install confirmation from OS appear after returning?

>Confirmation window (at fullscreen) appears when installation progress reaches 70%. But there is also a dialog from OS above this confirmation window. This dialog request to grant application permission to install apps from third-party sources. After permission granted the installation confirmation window disappears and we can observe a waiting circular loading indicator for some time. After the indicator disappears, the installer session ends with the error "Generic(message=Session {id} is dead.)".

>> Also, does install progress always reach 70% specifically when a session is committed, i.e. install confirmation appears?

>The install progress always reaches 70%. If we use setConfirmation(Confirmation.DEFERRED) there is no any confirmation window or permission dialog. The installation just hangs out without any errors. If we use setRequireUserAction(false) the installer session ends with the error "Generic(message=Session {id} is dead.)".

_Originally posted by @gizomo in https://github.com/solrudev/Ackpine/issues/74#issuecomment-2434021726_

**Comment by solrudev** [comment]
@gizomo
>After permission granted the installation confirmation window disappears

This is not typical behavior. It should not disappear after granting install permission, it should return to top to confirm installation from user. This needs further investigation.

Regarding the `Session {id} is dead.` failure. Please, try `0.7.7-20241024.040713-1` snapshot version. You need to add [Sonatype `snapshots` repository](https://s01.oss.sonatype.org/content/repositories/snapshots/) to your `settings.gradle(.kts)`.

>If we use setConfirmation(Confirmation.DEFERRED) there is no any confirmation window or permission dialog.

There must be a heads-up notification when `Confirmation.DEFERRED` is used. When clicked, it will start either user confirmation from OS (`requireUserAction=true`) or just proceed with installation (`requireUserAction=false`). If you don't see it, ensure you have configured notifications correctly. See https://github.com/solrudev/Ackpine/issues/66#issuecomment-2201870349 for info. This is not related to the `Session {id} is dead.` failure.

**Comment by gizomo** [comment]
@solrudev 

Sorry for the wait. I was busy working on a project. I checked version 0.8.0. Everything is the same.

**Comment by gizomo** [comment]
@solrudev

> Have you checked notifications configuration with `Confirmation.DEFERRED`?

I try and session stops at 70%. There are no any errors from SessionStateListener.

> * On what device/OS do you experience the issue?

I use different set top boxes with Android 7 and 9.

> * Where do you launch the session (in foreground/background, service, activity, etc.)?

Session is launched from foreground activity. When confirmation dialog appears the activity goes to the background and `onStop` is invoked.

> * When a session is launched, please log a value of `android.content.pm.PackageInstaller.mySessions`

`[android.content.pm.PackageInstaller$SessionInfo@e9e6e6f, android.content.pm.PackageInstaller$SessionInfo@7f5077c, android.content.pm.PackageInstaller$SessionInfo@1842805, android.content.pm.PackageInstaller$SessionInfo@254c05a]`

**Comment by solrudev** [comment]
@gizomo 
>I try and session stops at 70%. There are no any errors from SessionStateListener.

>I use different set top boxes with Android 7 and 9.

Now it makes sense. Android TV doesn't show notifications which are necessary to commit a session by clicking on them.

It turns out, on Android TV system package installer is behaving a bit differently when requesting install permission. I'll account for that in library's implementation and release a fix shortly.

**Comment by gizomo** [comment]
@solrudev 
> Now it makes sense. Android TV doesn't show notifications which are necessary to commit a session by clicking on them.

I'm not sure chinese set top boxes use Android TV. Usually, the Chinese flash the regular Android into the device.

**Comment by samjoshai** [comment]
@solrudev In my thread for this,  #74, our system is running a distribution of AOSP not Android TV, and we see this behavior.

**Comment by solrudev** [comment]
Fix is released in 0.8.1. Check if it resolves your issue.

**Comment by gizomo** [comment]
@solrudev 
Thanks a lot, everything works as it should.
