### ISSUE TITLE
Certain XAPK files can't be installed via Ackpine while they can be installed via SAI, error is not very informative

### ISSUE THREAD

**Issue by adi-vizgan-unplugged** [solrudev/Ackpine#95]
Hi,
I encountered a few XAPK files that can't be installed via Ackpine while they can be installed via SAI (https://play.google.com/store/apps/details?id=com.mtv.sai&hl=en).
The error I get in Ackpine is not very informative, see screenshot:
![Screenshot_20241212_120137](https://github.com/user-attachments/assets/1086e037-89ca-42f2-8666-c5e2258b0f14)

If there is a missing split, how can it be installed via SAI? And the app works very well after installing via SAI.
Here is the app I am trying to install:
https://play.google.com/store/apps/details?id=com.dotloop.mobile

You can download the XAPK from the link above using this website:
https://apk.support/apk-downloader

If you need more information LMK.

**Comment by solrudev** [comment]
@adi-vizgan-unplugged The app you're trying to install uses dynamic features, and they're not supported by Ackpine.

Thanks for the report, I'll think about dynamic features support implementation.

**Comment by solrudev** [comment]
Proper support for dynamic features was added in 0.9.1.

**Comment by adi-vizgan-unplugged** [comment]
Thanks @solrudev ! I haven't heard of dynamic features in APK splits, I'll check it out. Thanks for adding support for it also!
